### ISSUE TITLE
ros-melodic/qt_gui_cpp-0.4.1-r1 does not compile with qtcore-5.15.1-r1

### ISSUE THREAD

**Issue by flabrosse** [ros/ros-overlay#1004]
Subject says it all.

```
/var/tmp/portage/ros-melodic/qt_gui_cpp-0.4.1-r1/work/qt_gui_cpp-0.4.1_build-python3_6/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipqt_gui_cppPluginContext.cpp:177:131: error: use of deleted function ‘qt_gui_cpp::PluginContext& qt_gui_cpp::PluginContext::operator=(const qt_gui_cpp::PluginContext&)’
  177 |     reinterpret_cast< ::qt_gui_cpp::PluginContext *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::qt_gui_cpp::PluginContext *>(sipSrc);
      |                                                                                                                                   ^
```
