### ISSUE TITLE
ros-kinetic/opencv3 doesn't build with >=sci-libs/vtk-8.2.0

### ISSUE THREAD

**Issue by awesomebytes** [ros/ros-overlay#988]
Just a warning for anyone else that may run into it.

ros-kinetic/opencv3 is a snapshot of a tarball (with disabled tests and examples as explained [here](http://wiki.ros.org/opencv3)) which is a bit of a pain to recreate.

The errors look like this:
```bash
2020-05-18T06:25:45.1708233Z /tmp/gentoo/var/tmp/portage/ros-kinetic/opencv3-3.3.1-r5/work/opencv3-3.3.1/modules/viz/src/clouds.cpp: In constructor 'cv::viz::WCloud::WCloud(cv::InputArray, cv::InputArray, cv::InputArray)':
2020-05-18T06:25:45.1709811Z /tmp/gentoo/var/tmp/portage/ros-kinetic/opencv3-3.3.1-r5/work/opencv3-3.3.1/modules/viz/src/clouds.cpp:80:13: error: 'class vtkPolyDataMapper' has no member named 'ImmediateModeRenderingOff'
2020-05-18T06:25:45.1710700Z    80 |     mapper->ImmediateModeRenderingOff();
```

The workaround is, meanwhile 8.1 lasts in the gentoo tree, to mask >8.2. If it lasts a year, it will last until the EOL of Kinetic anyways. Alternatively, if it comes to it, we can add to ros-overlay in sci-libs the last 8.1 ebuild.

**Comment by awesomebytes** [comment]
Also, not directly related to that, but vtk-8.2.0 right now doesn't build correctly as it needs media-libs/glew and dev-libs/plugixml and they aren't declared in their dependencies, they must be emerged by hand first. As reported [here for glew](https://bugs.gentoo.org/723460) and [here for plugixml](https://bugs.gentoo.org/722770)
